// api_setting.js
module.exports = [
    { route: '/', file: './routes/index' },
    { route: '/users', file: './routes/users' },
    { route: '/db', file: './routes/db' },
    { route: '/contact', file: './routes/contact' },
    { route: '/login', file: './routes/login' },
    { route: '/logout', file: './routes/logout' },
    { route: '/about', file: './routes/about' },
    { route: '/packages', file: './routes/packages' },
    { route: '/services', file: './routes/services' },
    { route: '/destination', file: './routes/destination' },
    { route: '/team', file: './routes/team' },
    { route: '/testimonial', file: './routes/testimonial' },
    { route: '/booking', file: './routes/booking' },
    { route: '/myprofile', file: './routes/myprofile' },
    { route: '/register', file: './routes/register' },
    { route: '/privacy', file: './routes/privacy' },
    { route: '/404', file: './routes/404' },
    { route: '/cms-admin-api', file: './routes/cms-admin-api'},
    { route: '/cms-admin-api-authUser', file: './routes/cms-admin-api-authUser'},
    { route: '/cms-admin-api-member', file: './routes/cms-admin-api-member'},
    { route: '/cms-admin-api-enquiry', file: './routes/cms-admin-api-enquiry'},
    { route: '/cms-admin-api-package', file: './routes/cms-admin-api-package'},
    { route: '/cms-admin-api-subscription', file: './routes/cms-admin-api-subscription'},
    { route: '/cms-admin-api-company', file: './routes/cms-admin-api-company'}
  ];